#!/bin/bash
#SBATCH --job-name=bd_emb1k_r
#SBATCH --account=torch_pr_281_chemistry
#SBATCH --partition=a100_chemistry
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=48G
#SBATCH --time=24:00:00
#SBATCH --array=0-3
#SBATCH --output=slurm/logs/%A_%a_emb1k_resume.log
#SBATCH --error=slurm/logs/%A_%a_emb1k_resume.err

# ─────────────────────────────────────────────────────────────
# BayesDiff: RESUME 1000-step Sampling for remaining pockets
#
# Resumed from job 3387783 which timed out at 24h.
# 55/93 pockets done, 38 remaining.
# Uses per-shard remaining pocket lists.
# Outputs go to the SAME shard directories as before.
# ─────────────────────────────────────────────────────────────

set -euo pipefail

SHARD_INDEX="${SLURM_ARRAY_TASK_ID:-0}"

NUM_SAMPLES="${NUM_SAMPLES:-64}"
NUM_STEPS="${NUM_STEPS:-1000}"
DEVICE="${DEVICE:-cuda}"
PDBBIND_DIR="${PDBBIND_DIR:-external/targetdiff/data/test_set}"
TARGETDIFF_DIR="${TARGETDIFF_DIR:-external/targetdiff}"

# Per-shard remaining pocket lists (generated by diagnostics)
POCKET_LIST="data/splits/remaining_shard${SHARD_INDEX}.txt"

# Map shard -> original output directory (from job 3387783)
declare -A SHARD_DIRS
SHARD_DIRS[0]="results/embedding_1000step/20260305_085825_j3387783/shards/shard_0of4"
SHARD_DIRS[1]="results/embedding_1000step/20260305_085827_j3387783/shards/shard_1of4"
SHARD_DIRS[2]="results/embedding_1000step/20260305_085834_j3387783/shards/shard_2of4"
SHARD_DIRS[3]="results/embedding_1000step/20260305_085839_j3387783/shards/shard_3of4"

SHARD_DIR="${SHARD_DIRS[${SHARD_INDEX}]}"

mkdir -p slurm/logs "${SHARD_DIR}"

N_REMAINING=$(wc -l < "${POCKET_LIST}" | tr -d ' ')

echo "═══════════════════════════════════════════════════════════"
echo " BayesDiff: RESUME 1000-step (Shard ${SHARD_INDEX})"
echo "═══════════════════════════════════════════════════════════"
echo "Date:         $(date)"
echo "Node:         $(hostname)"
echo "GPU:          $(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null || echo 'N/A')"
echo "Shard dir:    ${SHARD_DIR}"
echo "Pocket list:  ${POCKET_LIST}"
echo "Remaining:    ${N_REMAINING} pockets"
echo "Samples/pkt:  ${NUM_SAMPLES}"
echo "Steps:        ${NUM_STEPS}"
echo ""

if [[ "${N_REMAINING}" -eq 0 ]] || [[ "${N_REMAINING}" -eq 1 && ! -s "${POCKET_LIST}" ]]; then
    echo "No remaining pockets for shard ${SHARD_INDEX}. Exiting cleanly."
    exit 0
fi

# ── Environment ──────────────────────────────────────────────
eval "$(/scratch/yd2915/miniconda3/bin/conda shell.bash hook)"
conda activate /scratch/yd2915/conda_envs/bayesdiff

export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

# ── Run sampling (direct call, not via shard script) ─────────
# We use 02_sample_molecules.py directly with per-shard pocket list
# since remaining pockets are already split.
python scripts/02_sample_molecules.py \
    --pocket_list "${POCKET_LIST}" \
    --pdbbind_dir "${PDBBIND_DIR}" \
    --targetdiff_dir "${TARGETDIFF_DIR}" \
    --num_samples "${NUM_SAMPLES}" \
    --num_steps "${NUM_STEPS}" \
    --device "${DEVICE}" \
    --output_dir "${SHARD_DIR}"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " Shard ${SHARD_INDEX} resume complete at $(date)"
echo " Output: ${SHARD_DIR}"
echo "═══════════════════════════════════════════════════════════"
